# Etapa única: Desarrollo

# Usar una imagen de Node que incluya herramientas de compilación
FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json (si existe)
COPY package*.json ./

# Instalar todas las dependencias, incluidas las de desarrollo
RUN npm install

# Copiar el resto de los archivos del proyecto
# (Aunque usaremos un volumen para el código fuente, es útil tenerlo por si se reconstruye sin el volumen)
COPY . .

# El servidor de desarrollo de React se ejecuta en el puerto 3000
EXPOSE 3000

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "start"] 