version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=https://xxxxx.supabase.co  # Tu URL de Supabase
      - CHOKIDAR_USEPOLLING=true
    command: npm start 