version: '3.3'

services:
  # Nginx Proxy Manager
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Nuevos puertos públicos no estándar
      - '8080:80'
      - '8443:443'
      # Puerto para acceder a la interfaz de admin
      - '81:81'
    volumes:
      - ./proxy-data:/data
      - ./letsencrypt:/etc/letsencrypt

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:password@db:5432/lista_compra
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=lista_compra
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  proxy-data: