# Etapa única: Desarrollo

# Usar una imagen de Node que incluya herramientas de compilación
FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json (si existe)
COPY package*.json ./

# Instalar todas las dependencias (incluidas las de desarrollo)
RUN npm install

# Copiar el resto de los archivos del proyecto
# (Al igual que con el frontend, esto es un fallback por si el volumen no está presente)
COPY . .

# El backend se ejecuta en el puerto 5000
EXPOSE 5000

# Usar nodemon para reiniciar automáticamente el servidor al detectar cambios
CMD ["npm", "run", "dev"] 